state_sa_name = "terraformaccount1844"
container_name = "akscs"
access_key = "dYM3LZ6Ig4MvsBMxvU6ITgTg2ockNJ8ZbmUNCtqB37rBCpA/ZGTlgfJQDok7FAJNq6a0y7ccCl0Z+ASt/8m7+g=="
prefix = "escs"
private_dns_zone_name = "privatelink.eastus.azmk8s.io"